export const demoSupportTicketsData = [
  {
    _id: 1,
    user: "alice@example.com",
    subject: "Unable to login to account",
    priority: "High",
    status: "Open",
    createdAt: "2h ago",
  },
  {
    _id: 2,
    user: "bob@example.com",
    subject: "Order not delivered",
    priority: "Urgent",
    status: "Pending",
    createdAt: "5h ago",
  },
  {
    _id: 3,
    user: "carol@example.com",
    subject: "Refund request for returned item",
    priority: "Medium",
    status: "Resolved",
    createdAt: "1d ago",
  },
  {
    _id: 4,
    user: "dave@example.com",
    subject: "Issue with payment processing",
    priority: "High",
    status: "Pending",
    createdAt: "3h ago",
  },
  {
    _id: 5,
    user: "emma@example.com",
    subject: "Wrong product received",
    priority: "Urgent",
    status: "Open",
    createdAt: "4d ago",
  },
  {
    _id: 6,
    user: "frank@example.com",
    subject: "Need invoice copy",
    priority: "Low",
    status: "Resolved",
    createdAt: "7h ago",
  },
  {
    _id: 7,
    user: "grace@example.com",
    subject: "Account verification issue",
    priority: "Medium",
    status: "Pending",
    createdAt: "2d ago",
  },
  {
    _id: 8,
    user: "henry@example.com",
    subject: "Order cancellation request",
    priority: "Low",
    status: "Resolved",
    createdAt: "8h ago",
  },
  {
    _id: 9,
    user: "irene@example.com",
    subject: "Change shipping address",
    priority: "Medium",
    status: "Open",
    createdAt: "6h ago",
  },
  {
    _id: 10,
    user: "jack@example.com",
    subject: "Multiple charges on card",
    priority: "High",
    status: "Pending",
    createdAt: "5d ago",
  },
  {
    _id: 11,
    user: "karen@example.com",
    subject: "Promo code not working",
    priority: "Low",
    status: "Open",
    createdAt: "1h ago",
  },
  {
    _id: 12,
    user: "leo@example.com",
    subject: "Damaged product received",
    priority: "Urgent",
    status: "Pending",
    createdAt: "9h ago",
  },
];
