export const demoUsersData = [
  {
    _id: "01",
    firstName: "John",
    lastName: "Doe",
    gender: "Male",
    email: "john.doe@example.com",
    role: "Seller",
    photo: "https://randomuser.me/api/portraits/men/1.jpg",
    birthday: "1990-05-15",
    bio: "Passionate about selling second-hand electronics and gadgets.",
    location: "Dubai, UAE",
    isVacation: false,
    isVerified: true,
    isBlocked: false,
    isDeleted: false,
  },
  {
    _id: "02",
    firstName: "Jane",
    lastName: "Smith",
    gender: "Female",
    email: "jane.smith@example.com",
    role: "Buyer",
    photo: "https://randomuser.me/api/portraits/women/2.jpg",
    birthday: "1985-08-20",
    bio: "Loves finding unique second-hand clothing.",
    location: "Abu Dhabi, UAE",
    isVacation: false,
    isVerified: true,
    isBlocked: false,
    isDeleted: false,
  },
  {
    _id: "03",
    firstName: "Michael",
    lastName: "Brown",
    gender: "Male",
    email: "michael.brown@example.com",
    role: "Seller",
    photo: "https://randomuser.me/api/portraits/men/3.jpg",
    birthday: "1992-11-10",
    bio: "Specializes in selling pre-loved footwear.",
    location: "Sharjah, UAE",
    isVacation: true,
    isVerified: true,
    isBlocked: true,
    isDeleted: false,
  },
  {
    _id: "04",
    firstName: "Emily",
    lastName: "Davis",
    gender: "Female",
    email: "emily.davis@example.com",
    role: "Buyer",
    photo: "https://randomuser.me/api/portraits/women/4.jpg",
    birthday: "1995-03-25",
    bio: "Enjoys shopping for vintage accessories.",
    location: "Ajman, UAE",
    isVacation: false,
    isVerified: true,
    isBlocked: false,
    isDeleted: false,
  },
  {
    _id: "05",
    firstName: "Chris",
    lastName: "Wilson",
    gender: "Male",
    email: "chris.wilson@example.com",
    role: "Admin",
    photo: "https://randomuser.me/api/portraits/men/5.jpg",
    birthday: "1988-07-12",
    bio: "Oversees platform operations and user management.",
    location: "Fujairah, UAE",
    isVacation: false,
    isVerified: true,
    isBlocked: false,
    isDeleted: false,
  },
  {
    _id: "06",
    firstName: "Sophia",
    lastName: "Taylor",
    gender: "Female",
    email: "sophia.taylor@example.com",
    role: "Seller",
    photo: "https://randomuser.me/api/portraits/women/6.jpg",
    birthday: "1993-09-18",
    bio: "Sells second-hand handbags and jewelry.",
    location: "Ras Al Khaimah, UAE",
    isVacation: false,
    isVerified: true,
    isBlocked: false,
    isDeleted: false,
  },
  {
    _id: "07",
    firstName: "Daniel",
    lastName: "Martinez",
    gender: "Male",
    email: "daniel.martinez@example.com",
    role: "Buyer",
    photo: "https://randomuser.me/api/portraits/men/7.jpg",
    birthday: "1997-01-05",
    bio: "Looking for affordable sportswear and gadgets.",
    location: "Umm Al Quwain, UAE",
    isVacation: false,
    isVerified: true,
    isBlocked: true,
    isDeleted: false,
  },
  {
    _id: "08",
    firstName: "Olivia",
    lastName: "Garcia",
    gender: "Female",
    email: "olivia.garcia@example.com",
    role: "Seller",
    photo: "https://randomuser.me/api/portraits/women/8.jpg",
    birthday: "1991-06-30",
    bio: "Specializes in selling pre-loved clothing.",
    location: "Dubai, UAE",
    isVacation: true,
    isVerified: true,
    isBlocked: false,
    isDeleted: false,
  },
  {
    _id: "09",
    firstName: "James",
    lastName: "Anderson",
    gender: "Male",
    email: "james.anderson@example.com",
    role: "Buyer",
    photo: "https://randomuser.me/api/portraits/men/9.jpg",
    birthday: "1983-04-22",
    bio: "Interested in vintage watches and accessories.",
    location: "Abu Dhabi, UAE",
    isVacation: false,
    isVerified: true,
    isBlocked: false,
    isDeleted: false,
  },
  {
    _id: "10",
    firstName: "Mia",
    lastName: "Hernandez",
    gender: "Female",
    email: "mia.hernandez@example.com",
    role: "Seller",
    photo: "https://randomuser.me/api/portraits/women/10.jpg",
    birthday: "1996-12-14",
    bio: "Sells second-hand home decor and furniture.",
    location: "Sharjah, UAE",
    isVacation: false,
    isVerified: true,
    isBlocked: true,
    isDeleted: false,
  },
  {
    _id: "11",
    firstName: "Ethan",
    lastName: "Clark",
    gender: "Male",
    email: "ethan.clark@example.com",
    role: "Admin",
    photo: "https://randomuser.me/api/portraits/men/11.jpg",
    birthday: "1987-02-17",
    bio: "Ensures smooth platform functionality and security.",
    location: "Ajman, UAE",
    isVacation: false,
    isVerified: true,
    isBlocked: false,
    isDeleted: false,
  },
  {
    _id: "12",
    firstName: "Isabella",
    lastName: "Lopez",
    gender: "Female",
    email: "isabella.lopez@example.com",
    role: "Buyer",
    photo: "https://randomuser.me/api/portraits/women/12.jpg",
    birthday: "1994-10-08",
    bio: "Loves finding unique second-hand books and collectibles.",
    location: "Fujairah, UAE",
    isVacation: false,
    isVerified: true,
    isBlocked: false,
    isDeleted: false,
  },
];
